# Generated by Django 3.1.5 on 2024-04-05 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='EventStare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=264, null=True)),
                ('stare', models.CharField(choices=[('Healthy', 'Healthy'), ('Unstable', 'Unstable'), ('Down', 'Down')], max_length=264, null=True)),
                ('detalii', models.CharField(max_length=264, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aplicatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=256, null=True)),
                ('descriere', models.CharField(max_length=624, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
