# Generated by Django 3.1.5 on 2024-04-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20240405_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='aplicatie',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='user',
        ),
        migrations.AddField(
            model_name='endpoint',
            name='cod_raspuns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='corp_raspuns',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='metoda_http',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='nume',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='stare',
            field=models.CharField(default='Unknown', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='timp_raspuns',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='ultima_verificare',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='url',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
