# Generated by Django 3.1.5 on 2024-04-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20240406_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='corp_raspuns',
        ),
    ]
