# Generated by Django 3.1.5 on 2024-04-06 11:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_endpoint_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventstare',
            name='detalii',
        ),
        migrations.RemoveField(
            model_name='eventstare',
            name='stare',
        ),
        migrations.AddField(
            model_name='eventstare',
            name='descriere',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventstare',
            name='endpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventuri_stare', to='my_app.endpoint'),
        ),
        migrations.AddField(
            model_name='eventstare',
            name='stare_noua',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventstare',
            name='stare_veche',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventstare',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
