# Generated by Django 3.1.5 on 2024-04-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20240406_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicatie',
            name='este_activa',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
