# Generated by Django 3.1.5 on 2024-04-06 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_aplicatie_este_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='aplicatie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.aplicatie'),
        ),
    ]
