# Generated by Django 3.1.5 on 2024-04-06 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_endpoint_aplicatie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriere', models.CharField(max_length=624, null=True)),
                ('este_rezolvat', models.BooleanField(default=False)),
                ('aplicatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.aplicatie')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.endpoint')),
            ],
        ),
    ]
