# Generated by Django 3.1.5 on 2024-04-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_bug'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicatie',
            name='stare',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Unstable', 'Unstable'), ('Down', 'Down')], max_length=256, null=True),
        ),
    ]
