# Generated by Django 3.1.5 on 2024-04-06 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_aplicatie_stare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicatie',
            name='stare',
            field=models.CharField(choices=[('Stable', 'Stable'), ('Unstable', 'Unstable'), ('Down', 'Down')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='endpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.endpoint'),
        ),
    ]
