# Generated by Django 3.1.5 on 2024-04-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_auto_20240406_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='cod_raspuns',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='stare',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='timp_raspuns',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='ultima_verificare',
        ),
    ]
