# Generated by Django 3.1.5 on 2024-04-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_auto_20240407_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicatie',
            name='stare',
        ),
        migrations.AddField(
            model_name='endpoint',
            name='stare',
            field=models.CharField(choices=[('Stable', 'Stable'), ('Unstable', 'Unstable'), ('Down', 'Down')], max_length=256, null=True),
        ),
    ]
