# Generated by Django 3.1.5 on 2024-04-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_auto_20240407_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='stare',
            field=models.CharField(choices=[('Stable', 'Stable'), ('Unstable', 'Unstable'), ('Down', 'Down')], default='Unknown', max_length=256, null=True),
        ),
    ]
