# Generated by Django 3.1.5 on 2024-04-07 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_remove_aplicatie_este_activa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='endpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.endpoint'),
        ),
    ]
