# Generated by Django 3.1.5 on 2024-04-07 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_auto_20240407_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='este_rezolvat',
        ),
        migrations.DeleteModel(
            name='EventStare',
        ),
    ]
