# Generated by Django 3.1.5 on 2024-04-07 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_verificare'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verificare',
        ),
    ]
