# Generated by Django 3.1.5 on 2024-04-07 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_delete_verificare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='user',
        ),
    ]
