# Generated by Django 3.1.5 on 2024-04-07 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0024_bug_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetariUtilizator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_verificare', models.IntegerField(default=60)),
                ('utilizator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setari', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
