# Generated by Django 3.1.5 on 2024-04-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0025_setariutilizator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setariutilizator',
            name='interval_verificare',
            field=models.CharField(default=60, max_length=264),
        ),
    ]
