# Generated by Django 3.1.5 on 2024-04-07 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0027_notificare'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificare',
        ),
    ]
